USE EMPRESA;

SELECT NOME, NUMERO
	FROM FUNCIONARIOS, TELEFONES
    WHERE FUNCIONARIOS.ID_FUNCIONARIO = TELEFONES.ID_FUNCIONARIO;
    

SELECT FUNCIONARIOS.NOME, DEPARTAMENTOS.NOME
	FROM FUNCIONARIOS, DEPARTAMENTOS
    WHERE FUNCIONARIOS.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO;

SELECT F.NOME, D.NOME AS DEPTO
	FROM 
		FUNCIONARIOS AS F, 
        DEPARTAMENTOS AS D
    WHERE F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
    ORDER BY F.NOME;

