-- INNER-JOIN-FUNCIONARIOS-DEPARTAMENTOS.SQL
USE EMPRESA;

SELECT F.NOME, F.SEXO, D.SIGLA
	FROM FUNCIONARIOS AS F
    INNER JOIN DEPARTAMENTOS AS D
    ON F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO; -- ON: CRITERIO QUE REALIZA A JUNÇÃO
   
-- FAÇAM UM INNER JOIN QUE APRESENTA OS FUNCIONARIOS COM SEUS NOMES E SALARIOS
-- JUNTO DE SEUS RESPECTIVOS TELEFONES, COM A OPERADORA E O TIPO
SELECT 
	F.NOME, F.SALARIO, T.NUMERO, T.OPERADORA, T.TIPO
    FROM FUNCIONARIOS AS F
    INNER JOIN TELEFONES AS T
    ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO;

-- EXPLICANDO A QUERY
SELECT 
	-- ENTRE O SELECT E O FROM VAO AS COLUNAS QUE SERAO EXIBIDIAS
	F.NOME, F.SALARIO, T.NUMERO, T.OPERADORA, T.TIPO
    -- FROM : É A TABELA QUE SERÁ USADA COMO BASE
    FROM FUNCIONARIOS AS F
    -- QUAL TABELA QUE IREI REALIZAR O CRUZAMENTO DOS DADOS
    INNER JOIN TELEFONES AS T
    -- QUAL O CRITERIO QUE SERÁ USADO PARA LIGAR UMA TABELA NA OUTRA
    -- PK <-> FK
    ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO;




