-- JOIN-COMPLETO.SQL
-- CRUZEM OS FUNCIONARIOS COM OS TELEFONES
-- E CRUZEM O RESULTADO COM DEPARTAMENTOS

SELECT F.NOME, T.NUMERO, D.NOME
	FROM FUNCIONARIOS AS F
    INNER JOIN TELEFONES AS T
		ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO
    INNER JOIN DEPARTAMENTOS AS D
		ON D.ID_DEPARTAMENTO = F.ID_DEPARTAMENTO
	ORDER BY F.NOME;