-- LEFT-JOIN-FUNCIONARIOS-TELEFONES
USE EMPRESA;

SELECT F.NOME, T.NUMERO
	FROM FUNCIONARIOS AS F
		LEFT JOIN TELEFONES AS T
			ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO
	WHERE F.SEXO = 'M' AND T.OPERADORA = 'VIVO';