USE EMPRESA;
SELECT * FROM DEPARTAMENTOS;
SELECT * FROM FUNCIONARIOS;
SELECT * FROM TELEFONES;


SELECT sexo, nome FROM FUNCIONARIOS;

-- ALIAS : APELIDO!
SELECT nome AS DEPARTAMENTO, sigla AS ABREVIATURA 
FROM DEPARTAMENTOS;

SELECT CONCAT('O nome é:', nome, ' e a sigla é: ', sigla)
AS RESUMO
FROM DEPARTAMENTOS;


SELECT DISTINCT(sexo) FROM FUNCIONARIOS;

SELECT DISTINCT(salario) FROM FUNCIONARIOS;

SELECT nome, salario, salario * 0.10 AS 'Bonus de 10%', 
salario + (salario * 0.10) AS 'Total'
FROM FUNCIONARIOS;



SELECT nome, salario FROM FUNCIONARIOS
WHERE sexo = 'M';

SELECT nome FROM FUNCIONARIOS
WHERE salario >= 5000;

-- FAÇA UMA QUERY QUE TRAGA OS FUNCIONARIOS QUE RECEBEM MENOS QUE 2000
-- E MOSTREM O NOME, O SALARIO, E QUANTO SERIA UM BONUS DE 5%
SELECT nome, salario, salario * 0.05 FROM FUNCIONARIOS
WHERE SALARIO <= 2000;


SELECT * FROM FUNCIONARIOS
WHERE dt_nascimento LIKE '2002-%';

SELECT * FROM FUNCIONARIOS
WHERE nome LIKE '_A%';


SELECT * FROM FUNCIONARIOS
WHERE sexo = 'F'
ORDER BY nome DESC;

SELECT * FROM FUNCIONARIOS
WHERE nome LIKE 'Paulo%'
ORDER BY nome;

SELECT nome, salario
	FROM funcionarios
    WHERE sexo = 'M'
    ORDER BY salario
    LIMIT 10;

SELECT * FROM FUNCIONARIOS
	WHERE DT_NASCIMENTO BETWEEN '2000-01-01' AND '2010-12-31'
    ORDER BY DT_NASCIMENTO;

SELECT * FROM FUNCIONARIOS
	WHERE SALARIO BETWEEN 2000 AND 3000.50;
    
SELECT nome FROM  DEPARTAMENTOS
WHERE sigla IN ('RH', 'CPD', 'DIR');

SELECT * FROM FUNCIONARIOS
	WHERE SALARIO IS NULL;
    
SELECT * FROM FUNCIONARIOS
	WHERE SALARIO IS NOT NULL
    ORDER BY SALARIO
    LIMIT 5;    


    

































