-- CTRL + ENTER : EXECUTA A LINHA ATUAL
USE AULA;
SHOW TABLES;
-- CRIANDO A TABELA
CREATE TABLE FUNCIONARIOS (
	id_funcionario INT,
    nome VARCHAR(45)
) ENGINE=InnoDB;
-- MOSTRA A ESTRUTURA DA TABELA
DESCRIBE FUNCIONARIOS;
DESC FUNCIONARIOS;
-- APAGAR UMA TABELA
DROP TABLE FUNCIONARIOS;
