DROP TABLE FUNCIONARIOS;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	id_funcionario INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    sexo CHAR(1) NOT NULL,
    PRIMARY KEY (id_funcionario)
) ENGINE=INNODB;

DESC FUNCIONARIOS;
