DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE IF NOT EXISTS EMPRESA;
USE EMPRESA;

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS (
	id_departamento INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sigla VARCHAR(10) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_departamento)
) ENGINE=INNODB;
-- CTRL + SHIFT + ENTER (executa TODO o arquivo)

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	id_funcionario INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    dt_nascimento DATE,
    dt_admissao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sexo CHAR(1) NOT NULL,
    salario DECIMAL(8,2),
    id_departamento INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_funcionario),
    CONSTRAINT FK_FUNCIONARIOS_DEPARTAMENTOS
		FOREIGN KEY (id_departamento)
        REFERENCES DEPARTAMENTOS (id_departamento)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TELEFONES (
	id_telefone INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ddd VARCHAR(3) NOT NULL,
    numero VARCHAR(15) NOT NULL,
    operadora VARCHAR(10),
    tipo VARCHAR(20) NOT NULL,
    id_funcionario INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_telefone),
    CONSTRAINT fk_TELEFONES_FUNCIONARIOS
			FOREIGN KEY (id_funcionario)
            REFERENCES FUNCIONARIOS (id_funcionario)
) ENGINE=INNODB;







