SHOW DATABASES;
USE AULA;
SHOW TABLES;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	id_funcionario INT UNSIGNED NOT NULL,
    nome VARCHAR(110) NOT NULL
) ENGINE=INNODB;

DESC FUNCIONARIOS;
DROP TABLE FUNCIONARIOS;
